apiVersion: apps/v1
kind: Deployment
metadata:
  name: plt-comm-customer-deployment
  namespace: plt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plt-comm-customer
  template:
    metadata:
      labels:
        app: plt-comm-customer
    spec:
      serviceAccountName: era-plt-service-account
      containers:
        - name: plt-comm-customer-container
          image: "212845026981.dkr.ecr.eu-central-1.amazonaws.com/nebim-era-plt-comm-customer-dev:0.0.93-95389af4a112b1392db3d71436282e0261b43057-0.8.5"
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_URLS
              value: "http://*:8080"
            - name: SERVICE_VERSION
              value: SERVICE_GIT_VERSION               
